# Generated by Django 2.1.4 on 2019-03-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190322_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Cart', unique=True),
        ),
        migrations.AlterField(
            model_name='orderonline',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Cart', unique=True),
        ),
    ]
