# Generated by Django 2.1.4 on 2019-03-22 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190322_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Cart'),
        ),
        migrations.AlterField(
            model_name='orderonline',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Cart'),
        ),
    ]
