# Generated by Django 2.1.4 on 2019-03-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20190324_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbyctt',
            name='order_id',
        ),
    ]
