# Generated by Django 2.1.4 on 2019-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_orderbyctt_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbyctt',
            name='order_id',
            field=models.CharField(default='Code_order', max_length=17),
        ),
    ]
