# Generated by Django 2.1.4 on 2019-03-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20190326_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbyctt',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
