# Generated by Django 2.1.4 on 2019-03-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_orderbyctt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
