# Generated by Django 2.1.4 on 2019-03-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20190327_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbyctt',
            name='slug',
        ),
    ]
