# Generated by Django 2.1.4 on 2019-03-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_orderbyctt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Cart'),
        ),
    ]
