# Generated by Django 2.1.4 on 2019-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20190330_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='order_id',
            field=models.CharField(default='Code_order', max_length=100),
        ),
    ]
