# Generated by Django 2.1.4 on 2019-04-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190306_2113'),
        ('payments', '0018_auto_20190405_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbyctt',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Item'),
        ),
    ]
