# Generated by Django 2.1.4 on 2019-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190306_2113'),
        ('payments', '0019_orderbyctt_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbyctt',
            name='items',
        ),
        migrations.AddField(
            model_name='orderbyctt',
            name='items',
            field=models.ManyToManyField(to='catalog.Item'),
        ),
    ]
