# Generated by Django 2.1.4 on 2019-04-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_auto_20190407_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbyctt',
            name='items',
        ),
        migrations.AddField(
            model_name='orderbyctt',
            name='items',
            field=models.CharField(default='', max_length=500),
        ),
    ]
