# Generated by Django 2.1.4 on 2019-04-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20190407_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='codigo_postal_1',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderbyctt',
            name='codigo_postal_2',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderbyctt',
            name='morada',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
