# Generated by Django 2.1.4 on 2019-04-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20190408_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='andar',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderbyctt',
            name='numero',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
