# Generated by Django 2.1.4 on 2019-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_auto_20190409_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyctt',
            name='ordered_through',
            field=models.CharField(choices=[('online', 'Online'), ('ctt', 'CTT')], default='', max_length=10),
        ),
    ]
