# Generated by Django 2.1.4 on 2019-04-09 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190226_2038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0025_auto_20190409_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderByCTT',
            new_name='Order',
        ),
    ]
