# Generated by Django 2.1.4 on 2019-02-16 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_material', models.CharField(choices=[('OUR', 'OURO'), ('PRT', 'PRATA'), ('OUT', 'OUTRO')], default='', max_length=5)),
                ('type_item', models.CharField(choices=[('ANL', 'ANEL'), ('CLR', 'COLAR'), ('BRC', 'BRINCOS'), ('PLS', 'PULSEIRA'), ('OUT', 'OUTRO')], default='', max_length=10)),
                ('reference', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='')),
                ('catalog', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Catalog')),
            ],
        ),
    ]
