# Generated by Django 2.1.4 on 2019-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190216_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='catalog/static/catalog/img'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(choices=[('ANÉIS', 'ANEL'), ('COLARES', 'COLAR'), ('BRINCOS', 'BRINCOS'), ('PULSEIRAS', 'PULSEIRA'), ('OUTROS', 'OUTRO')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_material',
            field=models.CharField(choices=[('OURO', 'OURO'), ('PRTA', 'PRATA'), ('AÇOS', 'AÇOS')], default='', max_length=5),
        ),
    ]
