# Generated by Django 2.1.4 on 2019-02-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190217_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type_Color',
            field=models.CharField(choices=[('DOURADO', 'DOURADO'), ('PRATEADO', 'PRATEADO'), ('BRONZE', 'BRONZE'), ('PRETO', 'PRETO'), ('BRANCO', 'BRANCO'), ('VERMELHO', 'VERMELHO'), ('AZUL', 'AZUL'), ('AMARELO', 'AMARELO'), ('CASTANHO', 'CASTANHO'), ('LARANJA', 'LARANJA'), ('ROSA', 'ROSA'), ('VIOLETA', 'VIOLETA'), ('VERDE', 'VERDE')], default='', max_length=20),
        ),
    ]
