# Generated by Django 2.1.4 on 2019-02-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_type_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type_Color',
        ),
        migrations.AddField(
            model_name='item',
            name='type_fornecedor',
            field=models.CharField(choices=[('Fornecedor1', 'Fornecedor1'), ('Fornecedor2', 'Fornecedor2'), ('Fornecedor3', 'Fornecedor3'), ('Fornecedor4', 'Fornecedor4'), ('Fornecedor5', 'Fornecedor5'), ('Fornecedor6', 'Fornecedor6'), ('Fornecedor7', 'Fornecedor7')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_item',
            field=models.CharField(choices=[('ANÉIS', 'Anéis'), ('COLARES', 'Colares'), ('BRINCOS', 'Brincos'), ('RELÓGIOS', 'Relógios'), ('PULSEIRAS', 'Pulseiras'), ('OUTROS', 'Outros')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_material',
            field=models.CharField(choices=[('OURO', 'Ouro'), ('PRTA', 'Prata'), ('AÇOS', 'Aços')], default='', max_length=5),
        ),
    ]
