# Generated by Django 2.1.4 on 2019-03-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190222_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='transferir.jpg', upload_to='static/catalog'),
        ),
    ]
