# Generated by Django 2.1.4 on 2019-03-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190302_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='transferir', upload_to='static/catalog'),
        ),
    ]
